# Generated by Django 4.2.1 on 2023-05-27 13:52

import ProteinPalaceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinPalaceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, to='ProteinPalaceApp.comment'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=ProteinPalaceApp.models.recipe_image_filename),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(upload_to=ProteinPalaceApp.models.user_profile_picture_filename),
        ),
    ]
